cc_library(
  name = "gmapping",
  srcs = glob([
          'gridfastslam/**/*.cpp',
          'gridfastslam/**/*.h',
          'gridfastslam/**/*.hxx',
          'scanmatcher/**/*.cpp',
          'scanmatcher/**/*.h',
          'scanmatcher/**/*.hxx',
          'sensor/**/*.cpp',
          'sensor/**/*.hxx',
          'sensor/**/*.h',
          'utils/**/*.cpp'
        ],
        exclude = [
          'gridfastslam/gfs2stream.cpp',
          'gridfastslam/gfs2log.cpp',
          'gridfastslam/gfs2stat.cpp',
          'gridfastslam/gfs2rec.cpp',
          'gridfastslam/gfs2neff.cpp',
          'scanmatcher/scanmatcher.new.cpp',
          'scanmatcher/scanmatch_test.cpp',
          'scanmatcher/scanmatch_test.cpp',
          'utils/autoptr_test.cpp',
          'utils/stat_test.cpp']),
  hdrs = glob(['include/**/*.h',
          'include/**/*.hxx',
          'include/**/*.hpp',
          'gridfastslam/**/*.h',
          'gridfastslam/**/*.hxx',
               'scanmatcher/**/*.h',
          'sensor/**/*.h*',
          "utils/**/*.h",
  ]),
  copts = ['-Wno-error'],
  licenses = ["unencumbered"],
  visibility = ["//visibility:public"],
)

