cc_library(
  name = "scanmatcher",
  srcs = glob([
			"*.cpp",
			"*.h"
		 ]),
   copts = ['-Wno-error'],
   visibility = ["//visibility:public"],
   include_prefix = "scanmatcher",
   deps = [
   		"//utils",
      "//grid",
      "//sensor"
   ]
)

